name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка .NET
        uses: dotnet/setup-dotnet@v1
        with:
          dotnet-version: '8.0.0'

      - name: Сборка проекта
        run: dotnet build

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка .NET
        uses: dotnet/setup-dotnet@v1
        with:
          dotnet-version: '8.0.0' 

      - name: Сборка проекта
        run: dotnet build
